version: 2

source: gwz_raw_data
name: raw
tables:
  - name: product
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: purchase_price
  - name: sales
    columns:
      - name: date_date
      - name: order_id
        tests:
          - unique
          - not_null
      - name: pdt_id
      - name: revenue
      - name: qty
  - name: ship
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null
      - name: shipping_fee
      - name: log_cost
      - name: ship_cost
